<?php
/*
 * Copyright (c) 2015 Juan José Torroglosa Ramón
 *
 * This file is part of the Cliphar package.
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

namespace Cliphar\Options;

use PHPUnit_Framework_TestCase;

class InputDefinitionParserTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var InputDefinitionParser
     */
    private $inputDefinitionParser;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->inputDefinitionParser = new InputDefinitionParser(
            new OptionDefinitionParser(),
            new ArgumentDefinitionParser()
        );
    }

    public function testOption()
    {
        $this->markTestIncomplete();
        $options = $this->inputDefinitionParser->parse('[option]');

        $this->assertEquals("option", $options["option"]->getName());
    }

    public function testOptionWithDefaultValue()
    {
        $this->markTestIncomplete();
        $options = $this->inputDefinitionParser->parse('[option]="default value"');

        $this->assertEquals("option", $options["option"]->getName());
        $this->assertEquals("default value", $options["option"]->getDefaultValue());
    }
    public function testTwoOptions()
    {
        $this->markTestIncomplete();
        $options = $this->inputDefinitionParser->parse('[option]="default value" [second_option]');

        $this->assertEquals("option", $options["option"]->getName());
        $this->assertEquals("default value", $options["option"]->getDefaultValue());
        $this->assertEquals("second_option", $options["second_option"]->getName());
    }
}