<?php
/**
 * Created by IntelliJ IDEA.
 * User: juanjo
 * Date: 10/8/15
 * Time: 19:58
 */

namespace Cliphar\Options;

use PHPUnit_Framework_TestCase;

class InputDefinitionParserTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var InputDefinitionParser
     */
    private $inputDefinitionParser;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->inputDefinitionParser = new InputDefinitionParser(
            new OptionDefinitionParser(),
            new ArgumentDefinitionParser()
        );
    }

    public function testOption()
    {
        $this->markTestIncomplete();
        $options = $this->inputDefinitionParser->parse('[option]');

        $this->assertEquals("option", $options["option"]->getName());
    }

    public function testOptionWithDefaultValue()
    {
        $this->markTestIncomplete();
        $options = $this->inputDefinitionParser->parse('[option]="default value"');

        $this->assertEquals("option", $options["option"]->getName());
        $this->assertEquals("default value", $options["option"]->getDefaultValue());
    }
    public function testTwoOptions()
    {
        $this->markTestIncomplete();
        $options = $this->inputDefinitionParser->parse('[option]="default value" [second_option]');

        $this->assertEquals("option", $options["option"]->getName());
        $this->assertEquals("default value", $options["option"]->getDefaultValue());
        $this->assertEquals("second_option", $options["second_option"]->getName());
    }
}